name: mackinect
description: "macKinect - modern cross-platform GUI for Proxmark3 (Iceman)."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_libserialport: ^0.6.0
  libserialport: ^0.3.0+1
  path_provider: ^2.1.5
  http: ^1.6.0
  archive: ^4.0.7
  crypto: ^3.0.6
  provider: ^6.1.5+1
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon_1024.png
    - assets/bundled/
